# Generated by Codex on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailGenerationHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("tone", models.CharField(max_length=50)),
                ("prompt", models.TextField()),
                ("variations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
