# Generated by Codex on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_api", "0002_emailgenerationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailgenerationhistory",
            name="attachment_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
