# Generated by Codex on 2026-03-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates_api", "0003_emailgenerationhistory_attachment_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailgenerationhistory",
            name="attachment_info",
        ),
    ]
