# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_api", "0006_alter_emailtemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="category",
            field=models.CharField(default="General", max_length=80),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
