# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_api", "0007_emailtemplate_category_tags_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
