from django.urls import path
from .views import (
    AccountStatsView,
    AccountCategoryView,
    ChangePasswordView,
    ClearArchivedTemplatesView,
    DatabaseTemplateListView,
    EmailHistoryView,
    EmailHistoryDetailView,
    ExportDataView,
    GetEmailLayoutView,
    GenerateEmailView,
    HealthCheckView,
    ImportTemplatesView,
    LoginView,
    LogoutView,
    MeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RenderAndDownloadTemplateView,
    RestoreTemplateView,
    SaveGeneratedHistoryView,
    ShareTemplateView,
    SignupView,
    TemplateDetailView,
    TemplateListCreateView,
    UploadEmailConfigView,
    UploadImageView,
    FavoriteTemplateView,
    VerificationStatusView,
)

urlpatterns = [
    path('health/', HealthCheckView.as_view()),
    path('auth/signup/', SignupView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('auth/me/', MeView.as_view()),
    path('auth/change-password/', ChangePasswordView.as_view()),
    path('auth/password-reset/', PasswordResetRequestView.as_view()),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view()),
    path('auth/verification/', VerificationStatusView.as_view()),
    path('account/stats/', AccountStatsView.as_view()),
    path('account/categories/', AccountCategoryView.as_view()),
    path('account/archived-templates/clear/', ClearArchivedTemplatesView.as_view()),
    path('account/export/', ExportDataView.as_view()),
    path('account/import-templates/', ImportTemplatesView.as_view()),
    path('getEmailLayout/', GetEmailLayoutView.as_view()),
    path('uploadImage/', UploadImageView.as_view()),
    path('uploadEmailConfig/', UploadEmailConfigView.as_view()),
    path('renderAndDownloadTemplate/', RenderAndDownloadTemplateView.as_view()),
    path('generateEmail/', GenerateEmailView.as_view()),
    path('history/', EmailHistoryView.as_view()),
    path('history/<int:history_id>/', EmailHistoryDetailView.as_view()),
    path('saveGeneratedHistory/', SaveGeneratedHistoryView.as_view()),
    path('templates/', TemplateListCreateView.as_view()),
    path('database-templates/', DatabaseTemplateListView.as_view()),
    path('templates/<int:template_id>/', TemplateDetailView.as_view()),
    path('templates/<int:template_id>/restore/', RestoreTemplateView.as_view()),
    path('templates/<int:template_id>/favorite/', FavoriteTemplateView.as_view()),
    path('templates/<int:template_id>/share/', ShareTemplateView.as_view()),
]
